FROM debian:stretch

RUN apt-get update && \
    apt-get install -y python3-dev python3-pip

# Install some Python3 libraries:
RUN mkdir /opt/software
ADD create_random_matrix.py /opt/software/
ADD requirements.txt /opt/software/
RUN pip3 install -r /opt/software/requirements.txt

ENTRYPOINT ["/bin/bash"]
